# -*- coding: utf-8 -*-
"""denoise an Image using Median Blur(openCV).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IDXvxSUS4xQOBGQfz1ucwQPd0k17ourk
"""

import cv2
import matplotlib.pyplot as plt
import numpy as np
import random

img = cv2.imread("pepper.webp")
img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

noisy = np.zeros(img.shape, np.uint8)

p = 0.2

for i in range(img.shape[0]):
    for j in range(img.shape[1]):
        r = random.random()
        if r < p/2:
            noisy[i][j] = [0, 0, 0] #black noise
        elif r < p:
            noisy[i][j] = [255, 255, 255] #white noise
        else:
            noisy[i][j] = img[i][j] # original img

#median blur
denoised = cv2.medianBlur(noisy, 5)

op = [img, noisy, denoised]

titles = ["original", 'noisy', 'denoised']

for i in range(3):
    plt.subplot(1, 3, i+1)
    plt.imshow(op[i])
    plt.title(titles[i])
    plt.xticks([])
    plt.yticks([])
plt.show()